<?xml version="1.0"?>
<cars>
 <car>
    <id>1</id>
    <reg_num>pn52bbp</reg_num>
    <Make>citroen</Make>
    <Model>c2</Model>
    <reg_year>2002-03-07</reg_year>
    <fuel_type>petrol</fuel_type>
    <no_of_doors>5</no_of_doors>
  </car>
 <car>
    <id>2</id>
    <reg_num>jl57bnm</reg_num>
    <Make>vauxhall</Make>
    <Model>astra</Model>
    <reg_year>2007-07-20</reg_year>
    <fuel_type>petrol</fuel_type>
    <no_of_doors>5</no_of_doors>
  </car>
 <car>
    <id>3</id>
    <reg_num>po60tuy</reg_num>
    <Make>volkswagen</Make>
    <Model>polo</Model>
    <reg_year>2010-01-09</reg_year>
    <fuel_type>diesel</fuel_type>
    <no_of_doors>5</no_of_doors>
  </car>
 <car>
    <id>4</id>
    <reg_num>ae09plm</reg_num>
    <Make>kia</Make>
    <Model>ceed</Model>
    <reg_year>2009-02-03</reg_year>
    <fuel_type>petrol</fuel_type>
    <no_of_doors>3</no_of_doors>
  </car>
</cars>
